### ISSUE TITLE
Compile Error for iso14443a

### ISSUE THREAD

**Issue by JohnDoeIsKIng** [RfidResearchGroup/proxmark3#2834]
Dear community,
dear Iceman,

the current github-state isn't able to compile on my system (Ubuntu 18.04, gcc 13.1.0).
The error message reads:
`[-] CC iso14443a.c
iso14443a.c:155:17: error: initializer element is not constant
     .frames = { WUPA_CMD },
                 ^~~~~~~~
iso14443a.c:155:17: note: (near initialization for 'WUPA_POLLING_PARAMETERS.frames[0]')
iso14443a.c:161:17: error: initializer element is not constant
     .frames = { REQA_CMD },
                 ^~~~~~~~
iso14443a.c:161:17: note: (near initialization for 'REQA_POLLING_PARAMETERS.frames[0]')
iso14443a.c:179:17: error: initializer element is not constant
     .frames = { WUPA_CMD },
                 ^~~~~~~~
iso14443a.c:179:17: note: (near initialization for 'hf14a_polling_parameters.frames[0]')
../common_arm/Makefile.common:118: recipe for target 'obj/iso14443a.o' failed
make[1]: *** [obj/iso14443a.o] Error 1
Makefile:167: recipe for target 'armsrc/all' failed
`

Any hints what to do?
Regards

JD.

**Comment by iceman1001** [comment]
Pull latest and see if you get issues.  Some refactoring was needed.
