### ISSUE TITLE
Fails to compile in Raspberry Pi 5 (aarch64)

### ISSUE THREAD

**Issue by pyllyukko** [RfidResearchGroup/proxmark3#3394]
Proxmark (version 8fbec33) fails to compile in Raspberry Pi 5 running Debian 13.5.

It fails with the following error:

```
[-] CC src/cmdmad.c
In function ‘parse_sector_ranges’,
    inlined from ‘CmdMADEncode’ at src/cmdmad.c:526:24:
src/cmdmad.c:470:30: error: writing 16 bytes into a region of size 8 [-Werror=stringop-overflow=]
  470 |             sectors[count++] = (uint8_t)s;
      |             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
src/cmdmad.c: In function ‘CmdMADEncode’:
src/cmdmad.c:525:17: note: at offset [32, 40] into destination object ‘sectors’ of size 40
  525 |         uint8_t sectors[40] = {0};
      |                 ^~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:1166: obj/cmdmad.o] Error 1
make[1]: *** [Makefile:186: client/all] Error 2
make[1]: Leaving directory '/home/pyllyukko/git/proxmark3'
make: *** [Makefile:41: all] Error 1
```

**Comment by bjornjulian00** [comment]
Alright, I just figured out why this is happening:

1. GCC 14+ versions now error out with some warnings where old versions would keep going.
2. ARM64 hosts cause this warning because GCC tries to vectorize the problematic function writes while x86 doesn't.
3. Thus, ARM64 hosts running GCC 14+ error out.

This is really easy to fix, just add "NOERROR=1" to your build flags, so:

`make NOERROR=1`

Or, if you don't want to blindly suppress all warnings, you can put this on line 547 (the parse_sector_ranges function) around the problematic bit:

```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstringop-overflow"
           sectors[count++] = (uint8_t)s;
#pragma GCC diagnostic pop
```

**Comment by iceman1001** [comment]
sounds like we need a proper fix instead of using `#pragma`  to silence the issue

**Comment by DidierA** [comment]
in `CmdMADEncode()`, replacing the line 
```
        uint8_t sectors[40] = {0};
```
with 
```
        uint8_t sectors[48] = {0};
```
is sufficient to suppress the warning (tested on ODroid-HC4 with cortex A55 inside (aarch64)).

I guess what gcc is telling us  is that with the optimizations on, it will copy chunks of 16 bytes at a time in the destination, so when arrived at offset 32 it will overflow an object of size 40.

**Comment by iceman1001** [comment]
Isn't this one fixed?

**Comment by DidierA** [comment]
It was not when I tested it yesterday with the latest commit available.

**Comment by iceman1001** [comment]
Now its fixed :)

**Comment by DidierA** [comment]
Sorry, but I still encounter the same problem with commit 12a890f :
```
$ make V=1

===================================================================
Version info:      Iceman/master/v4.21611-1191-g12a890f44-dirty
Platform name:     Proxmark3 RDV4
PLATFORM:          PM3RDV4
PLATFORM_FPGA:     xc2s30
PLATFORM_SIZE:     512
Platform extras:   No extra selected
Included options:  SMARTCARD FLASH -DRDV4 -DCHIP_AT91SAM7S LF HITAG EM4x50 EM4x70 ZX8211 GENERAL_HF ISO15693 LEGICRF ISO14443b ISO14443a ICLASS SEOS FELICA NFCBARCODE HFSNIFF HFPLOT COMPRESSION
Standalone mode:   LF_SAMYRUN
===================================================================
[...]
cc -MT obj/cmdmad.o -MMD -MP -MF obj/cmdmad.Td -Wall -Werror -O3 -fstrict-aliasing -pipe -Wbad-function-cast -Wredundant-decls -Wmissing-prototypes -Wchar-subscripts -Wshadow -Wundef -Wwrite-strings -Wunused -Wuninitialized -Wpointer-arith -Winline -Wformat -Wformat-security -Winit-self -Wmissing-include-dirs -Wnested-externs -Wmissing-declarations -Wempty-body -Wignored-qualifiers -Wmissing-field-initializers -Wtype-limits -Wold-style-definition -Wcast-align -Wswitch-enum -Wstringop-overread -Wstringop-overflow -Wstrict-prototypes -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -ftrivial-auto-var-init=zero -fPIC -fstack-clash-protection  -O3  -I./src -I./include -I../include -I../common -I../common_fpga -I./deps/amiitool -I./deps/cliparser -I./deps/hardnested -I./deps/id48/src/../public -I./deps/liblua -I./deps/jansson -I../common/mbedtls -I./deps/reveng -I./deps/openjpeg -I./deps/tinycbor -I./deps/whereami -I./deps/mqtt -I./deps/vec   -isystem /usr/include/python3.13  -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/aarch64-linux-gnu -I/usr/include/webp -DAVIF_DLL -I/usr/include/rav1e -I/usr/include/svt-av1 -DEB_DLL   -DHAVE_READLINE -DHAVE_BLUEZ -DHAVE_PYTHON -DHAVE_GD -DHAVE_ZLIB -DHAVE_LUA_SWIG -DHAVE_PYTHON_SWIG -DHAVE_SNPRINTF -DHAVE_GUI -DOPJ_STATIC -c -o obj/cmdmad.o src/cmdmad.c
In function ‘parse_sector_ranges’,
    inlined from ‘CmdMADEncode’ at src/cmdmad.c:605:24:
src/cmdmad.c:547:30: error: writing 16 bytes into a region of size 8 [-Werror=stringop-overflow=]
  547 |             sectors[count++] = (uint8_t)s;
      |             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
src/cmdmad.c: In function ‘CmdMADEncode’:
src/cmdmad.c:604:17: note: at offset [32, 40] into destination object ‘sectors’ of size 40
  604 |         uint8_t sectors[40] = {0};
      |                 ^~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:1202: obj/cmdmad.o] Error 1
make[1]: *** [Makefile:186: client/all] Error 2
make[1]: Leaving directory '/home/didier/proxmark3'
make: *** [Makefile:41: all] Error 1
```
changing `sectors[40]` to  `sectors[48]` in line 604 of `client/src/cmdmad.c` solves it.

gcc version: `gcc (Debian 14.2.0-19) 14.2.0`  on `Linux 6.6.0-odroid-arm64 #1 SMP PREEMPT Mon, 04 Nov 2024 09:52:06 +0000 aarch64 GNU/Linux`

**Comment by pyllyukko** [comment]
> Sorry, but I still encounter the same problem with commit [12a890f](https://github.com/RfidResearchGroup/proxmark3/commit/12a890f444bf5f04e6897470c0f6bf1badfdadba)

Same here.
