### ISSUE TITLE
cmdhw.c:629:9: error: ‘__builtin_memcpy’ writing 47 bytes into a region of size 37 overflows the destination [-Werror=stringop-overflow=]

### ISSUE THREAD

**Issue by strasharo** [RfidResearchGroup/proxmark3#368]
**Describe the bug**
Trying to build the latest HEAD on Fedora 30 with PM3OTHER platform fails with the following exception:
```
[-] CC cmdlfcotag.c
cmdhw.c: In function ‘pm3_version’:
cmdhw.c:629:9: error: ‘__builtin_memcpy’ writing 47 bytes into a region of size 37 overflows the destination [-Werror=stringop-overflow=]
  629 |         strcat(msg + strlen(msg), _YELLOW_("GCC "__VERSION__));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:418: obj/cmdhw.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:55: client/all] Error 2
```
Using git bisect I found that the issue appeared since this commit:
https://github.com/RfidResearchGroup/proxmark3/commit/4e627f09c017ea3ac22c66933eec3de5a7eb94ea

**To Reproduce**
Steps to reproduce the behavior on Fedora 30 x86_64:
1. git clone https://github.com/RfidResearchGroup/proxmark3.git
2. cd proxmark3
3. cp Makefile.platform.sample Makefile.platform
4. edit Makefile.platform and set PLATFORM=PM3OTHER
5. make clean
6. make
7. Get the folowing exception:
```
[-] CC cmdlfcotag.c
cmdhw.c: In function ‘pm3_version’:
cmdhw.c:629:9: error: ‘__builtin_memcpy’ writing 47 bytes into a region of size 37 overflows the destination [-Werror=stringop-overflow=]
  629 |         strcat(msg + strlen(msg), _YELLOW_("GCC "__VERSION__));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:418: obj/cmdhw.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:55: client/all] Error 2

```

**Expected behavior**
It should be as it did before.

**Desktop (please complete the following information):**
 - OS: Fedora 30 x86_64

**Additional context**
gcc (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by doegox** [comment]
Thanks, should be fixed by https://github.com/RfidResearchGroup/proxmark3/commit/aa77f7298c18c22dda15673d518093b6f0f0e55e

**Comment by strasharo** [comment]
Thanks for the fast response, retried with the latest HEAD and got this:
```

[-] CC cmdhw.c
cmdhw.c: In function ‘pm3_version’:
cmdhw.c:633:9: error: ‘__builtin_memcpy’ writing 47 bytes into a region of size 39 overflows the destination [-Werror=stringop-overflow=]
  633 |         strcat(msg + strlen(msg), _YELLOW_(PM3CLIENTCOMPILER __VERSION__));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [Makefile:418: obj/cmdhw.o] Error 1
make: *** [Makefile:55: client/all] Error 2

```

**Comment by doegox** [comment]
sigh... :) let me check

**Comment by doegox** [comment]
try again, I simplified the code

**Comment by strasharo** [comment]
Thanks a lot, builds and flashes fine now. :)

**Comment by iceman1001** [comment]
Excellent @doegox 
I think the ascii colors might have made the string longer.  We calculated string length before adding it.

**Comment by strasharo** [comment]
@iceman1001 , with the latest commits now I get this:

```
[-] CC cmdhw.c
cmdhw.c: In function ‘pm3_version’:
cmdhw.c:676:66: error: expected ‘)’ before ‘PM3HOSTOS’
  676 |         PrintAndLogEx(NORMAL, "Client: RRG/Iceman compiled with " _YELLOW_(PM3CLIENTCOMPILER __VERSION__) " on " _YELLOW_(PM3HOSTOS));
      |                                                                  ^
      |                                                                  )
cmdhw.c:692:49: error: expected ‘)’ before ‘PM3HOSTOS’
  692 |         PrintAndLogEx(NORMAL, "  compiled with " PM3CLIENTCOMPILER __VERSION__ " on " PM3HOSTOS);
      |                                                 ^                                     ~~~~~~~~~
      |                                                 )
make[1]: *** [Makefile:418: obj/cmdhw.o] Error 1
make: *** [Makefile:55: client/all] Error 2

```

**Comment by iceman1001** [comment]
ha,  on mingw (ps32) it compiles,  switched over to wsl,  and it fails.

**Comment by iceman1001** [comment]
try again

**Comment by strasharo** [comment]
Compiles fine now, thanks a lot. :)
